version: '3.4'

networks:
  dev:
    driver: bridge

services:
  eshopmicroservice:
    image: ${DOCKER_REGISTRY-}eshopmicroservice
    depends_on:
      - "postgres"
    ports:
      - "50333:80"
      - "443:443"
    build:
      context: .
      dockerfile: EshopMicroservice\Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=postgres;Port=5432;Database=homework_hdv2;User Id=postgres;Password=postgres;Pooling=true;
    networks:
      - dev
      
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: homework_hdv2
    ports:
       - "5433:5432"
    networks:
       - dev